import turtle
a=turtle.Turtle()
a.shape("turtle")
a.color()
a.forward(100)
a.color("red")
a.forward(100)
a.color("blue","green")
a.backward(300)
turtle.colormode(255)
a.color(120,40,50)
wn = turtle.Screen()
wn.bgcolor("pink")
turtle.colormode()
turtle.colormode(255)
wn.bgcolor(170,30,20)
wn.title("KZT")
